#!/bin/bash

# Lemaiyan's Travels - Git Setup Script
# This script helps you initialize Git and push to GitHub

echo "🌍 Setting up Lemaiyan's Travels Git Repository..."

# Check if Git is installed
if ! command -v git &> /dev/null; then
    echo "❌ Git is not installed. Please install Git first."
    exit 1
fi

# Initialize Git repository
if [ ! -d ".git" ]; then
    echo "📦 Initializing Git repository..."
    git init
else
    echo "✅ Git repository already exists"
fi

# Create .gitignore if it doesn't exist
if [ ! -f ".gitignore" ]; then
    echo "📝 Creating .gitignore file..."
    cat > .gitignore << EOF
# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/
build
dist/

# Production
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
public

# Storybook build outputs
.out
.storybook-out

# Temporary folders
tmp/
temp/

# Logs
logs
*.log

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
public

# Storybook build outputs
.out
.storybook-out

# Temporary folders
tmp/
temp/

# Editor directories and files
.vscode/
.idea/
*.swp
*.swo
*~

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
EOF
    echo "✅ .gitignore created"
else
    echo "✅ .gitignore already exists"
fi

# Add all files to Git
echo "📁 Adding files to Git..."
git add .

# Check if there are files to commit
if git diff --cached --quiet; then
    echo "⚠️  No changes to commit"
else
    # Make initial commit
    echo "💾 Making initial commit..."
    git commit -m "Initial commit: Lemaiyan's Travels website

🌍 Features:
- Modern Next.js 14 with TypeScript
- Responsive design with TailwindCSS
- Beautiful animations with Framer Motion
- Multi-page travel agency website
- Contact forms and content management
- SEO optimized and performance ready

📦 Tech Stack:
- Next.js 14 (App Router)
- TypeScript
- TailwindCSS
- Framer Motion
- Lucide React Icons
- React Hook Form with Zod

🎨 Pages:
- Home with hero and services
- About page
- Services detail page
- Tours (coming soon)
- Blog page
- Contact page with form
- Privacy policy

🚀 Ready for deployment to Vercel, Netlify, or traditional hosting"
fi

echo "✅ Git setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Create a new repository on GitHub: https://github.com/new"
echo "2. Name it 'lemaiyans-travels'"
echo "3. Don't initialize with README (you already have one)"
echo "4. Run these commands to connect to GitHub:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/lemaiyans-travels.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "🌐 After pushing to GitHub, you can deploy to:"
echo "   - Vercel (recommended): https://vercel.com"
echo "   - Netlify: https://netlify.com"
echo "   - See DEPLOYMENT_GUIDE.md for detailed instructions"
echo ""
echo "🎉 Your Lemaiyan's Travels website is ready for deployment!"
